name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "includes"
  steps:
    - run: echo Good-bye ${{ inputs.who-to-greet }}.
      shell: bash
    - uses: actions/checkout@v1
