name: Super-Linter

on: [push, workflow_dispatch]

jobs:
  # ジョブキーを設定する。 ジョブ名が指定されていない場合、
  # キーはジョブ名として表示される
  super-lint:
    # ジョブ名を付ける
    name: Lint code base
    # 実行するマシンのタイプを設定する
    runs-on: ubuntu-latest

    steps:
      # ubuntu-latest マシンでリポジトリのコピーをチェックアウトする
      - uses: actions/checkout@v2
      - includes: ./composite-action
      #- uses: actions/hello-world-composite-run-steps-action@v1
